on:
    push:
      branches: [ "master" ]
    pull_request:
      branches: [ "master" ]

name: 🚀 CNAD

jobs:

    build:
        name: Build
        runs-on: ubuntu-latest
        
        steps:
            - name: Clone repository
              uses: actions/checkout@v3

            - name: Use Node.js 16.x
              uses: actions/setup-node@v3
              with:
                node-version: 16

            - name: Install dependencies
              run: npm ci

            - name: Run build if present
              run: npm run build --if-present

            - name: Run npm test
              run: npm test

    web-deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest
        needs: [build]

        steps:
            - name: Clone repository
              uses: actions/checkout@v3

            - name: Creating restart file
              run: |
                mkdir tmp && touch tmp/restart.txt 
                echo $RANDOM > tmp/restart.txt

            - name: 📂 Sync files
              uses: SamKirkland/FTP-Deploy-Action@4.3.2
              with:
                server: ${{ secrets.FTP_HOST }}
                username: ${{ secrets.FTP_USER }}
                password: ${{ secrets.FTP_PASSWORD }}
                exclude: |
                    **/.github/**
                    **/.git/**
                    .gitignore